# nightwind completion                                     -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_nightwind_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compline="${COMP_WORDS[@]:1:$COMP_CWORD-1}"

  case "$compline" in
    'composer'*)
      COMPREPLY=($(compgen -W "--container --help -h" -- "$cur"))
      ;;

    'artisan'*)
      COMPREPLY=($(compgen -W "--container --help -h" -- "$cur"))
      ;;

    'render'*)
      COMPREPLY=($(compgen -W "--help --rebuild --remove -h" -- "$cur"))
      ;;

    'build'*)
      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
      ;;

    'mysql'*)
      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
      ;;

    'nginx'*)
      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
      ;;

    'redis'*)
      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
      ;;

    'exec'*)
      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
      ;;

    'down'*)
      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
      ;;

    'nuke'*)
      COMPREPLY=($(compgen -W "--force --help -h" -- "$cur"))
      ;;

    'init'*)
      COMPREPLY=($(compgen -W "--force --help -h" -- "$cur"))
      ;;

    'logs'*)
      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
      ;;

    'app'*)
      COMPREPLY=($(compgen -W "--help -h" -- "$cur"))
      ;;

    'npm'*)
      COMPREPLY=($(compgen -W "--container --help -h" -- "$cur"))
      ;;

    'up'*)
      COMPREPLY=($(compgen -W "--force --help -h" -- "$cur"))
      ;;

    *)
      COMPREPLY=($(compgen -W "--help --version -h -v app artisan build composer down exec init logs mysql nginx npm nuke redis render up" -- "$cur"))
      ;;

  esac
} &&
complete -F _nightwind_completions nightwind

# ex: filetype=sh
