# nightwind completion                                     -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_nightwind_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compline="${COMP_WORDS[@]:1:$COMP_CWORD-1}"

  case "$compline" in
    'init'*)
      COMPREPLY=($(compgen -W "--force --help -h" -- "$cur"))
      ;;

    'i'*)
      COMPREPLY=($(compgen -W "--force --help -h" -- "$cur"))
      ;;

    *)
      COMPREPLY=($(compgen -W "--help --version -h -v i init" -- "$cur"))
      ;;

  esac
} &&
complete -F _nightwind_completions nightwind

# ex: filetype=sh
