#!/bin/bash
# run this script during local dev to automatically run "bashly generate" when ./src changes.
inotifywait -q -m -e modify -e create -e close_write --format "%w%f"  ./src/* | \
while read -r filename event; do
    # https://stackoverflow.com/questions/28195821/how-can-i-interrupt-or-debounce-an-inotifywait-loop
    jobs -p | xargs kill -9 2>/dev/null
    (
        ./generate

        sleep 5 
    ) &
done
