#!/bin/bash
docker run --rm --user $(id -u):$(id -g) --volume "$PWD:/app" dannyben/bashly generate
docker run --rm --user $(id -u):$(id -g) --volume "$PWD:/app" dannyben/bashly add comp script --force