name: build
alias: b
help: Build docker image(s) in .nightwind/dockerfiles.
catch_all: true
filename: commands/build
filters:
  - is_laravel_directory
  - docker_running
  - requires_variables
dependencies:
  - docker
  - find
args:
- name: target
  help: The image to build, if excluded will build all in the dockerfiles directory. Should exist in .nightwind/dockerfiles/<target>.Dockerfile