name: up
alias: u
help: Start docker compose services.
catch_all: true
filename: commands/up
filters:
  - is_laravel_directory
  - docker_running
  - env_file_required
  - requires_variables
  - requires_rendered_files
dependencies:
  - docker
  - find
flags:
- long: --force
  help: Overwrite existing files.
    