#!/bin/bash
variables_file=".nightwind/variables.yaml"
eval $(yaml_load $variables_file)

container="${args[--container]}"
command="${args[command]}"
container="$tag_prefix-${container/$tag_prefix-/''}"

cyan "Running: docker exec -it "$container" php artisan $command $other_args"
docker exec -it $container php artisan $command $other_args