#!/bin/bash

# Build .nightwind/rendered/dockerfiles images.

target="${args[target]}"

if [ ! -d ".nightwind/rendered/dockerfiles" ];
then
    echo "$(red .nightwind/rendered/dockerfiles doesnt exist, nothing to build.)"
    exit 1
fi

docker_tag_namespace="$(grep -o '"docker_tag_namespace": "[^"]*' .nightwind/variables.json | grep -o '[^"]*$')"

if [ -z $docker_tag_namespace ];
then
    echo "$(red MissingVariableError:) $(bold The docker_tag_namespace json variable is required to build images.)"
    exit 1;
fi

build_project_images "$target" other_args