#!/bin/bash

# Initialize project .nightwind folder.
domain=${args[--domain]}

mkdir -p ".nightwind"

current_dir=$(pwd)

make_stub(){
    file=$1
    relative_path="${file##*stubs/}" 
    destination_path=".nightwind/$relative_path" 
    mkdir -p "$(dirname $destination_path)" ## ensure parent directory exists
    make_file $destination_path ".nightwind/$stub_type/$relative_path" "$(cat $file)" ${args[--force]}
}

## generate stubs directory/files except variables.yml as thats's been handled explictly above.
for template in $(find $(get_cli_path)/stubs -type f ! -name variables.yaml.blade); 
do 
    make_stub $template
done

# create a .gitignore to ignore rendered files
if [ ! -f ".nightwind/.gitignore" ];
then 
    echo -e "rendered/" > ".nightwind/.gitignore"
fi

lightgreen "Initialized .nightwind directory & files."