#!/usr/bin/env php
<?php

/**
 * ---------------------------------------------------------------------------------------------------
 * This script is part of the nightwind-cli, it is used internally by the `nightwind render` command
 * for generating your `.nightwind/template` rendered files. Changing this file is not recommended
 * unless you have some custom needs not met by the cli natively.
 * ---------------------------------------------------------------------------------------------------
 */
require_once 'vendor/autoload.php';


use BladeCLI\Blade;
use Illuminate\Container\Container;
use Illuminate\Filesystem\Filesystem;

$options = [];

$blade = new Blade(
    container: new Container,
    filesystem: new Filesystem,
    filePath: '/path/to/file/to/render',
    options: $options
);

dd($blade);